name: 'Pull Request State'
description: ''
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  PR_NUMBER:
    description: 'Pull request number'
    required: true
outputs:
  pullRequestState:
    description: 'pull request state'
runs:
  using: 'node12'
  main: 'dist/index.js'